language: ruby
rvm:
  - 2.0.0
  - 1.9.3
  - jruby-19mode
  - rbx-19mode
  - ruby-head
  - jruby-head
jdk:
  - oraclejdk7
  - openjdk7
matrix:
  exclude:
    - rvm: 2.0.0
      jdk: openjdk7
    - rvm: 1.9.3
      jdk: openjdk7
    - rvm: rbx-19mode
      jdk: openjdk7
    - rvm: ruby-head
      jdk: openjdk7
